### ISSUE TITLE
Sick/Vacation Balances: Crashing

### ISSUE THREAD

**Issue by poolguy** [byu-oit-appdev/android-byu-suite-v2#164]
Name of Tester: Seth
Feature: Cougar Cash

How to produce error:
Not certain if it's just the phone I'm using, but the feature crashes every time I open it

**Comment by coreywoodfield** [comment]
On my phone, it doesn't crash, but an error dialog does pop up that says the standard error message. I assume it's because I'm not an employee and therefore don't have any sick / vacation balances, but we should probably check for that like iOS does and say No Sick/Vacation balances were found or something like that
